# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-05-13 13:51
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Website', '0002_userprofile'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='gender',
            field=models.CharField(choices=[('M', 'M'), ('F', 'F')], default='Select Gender', max_length=1),
        ),
    ]
