# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-05-13 14:35
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Website', '0003_userprofile_gender'),
    ]

    operations = [
        migrations.AlterField(
            model_name='items',
            name='category',
            field=models.CharField(choices=[('Stationary', 'Stationary'), ('Confectionary', 'Confectionary'), ('Garments', 'Garments')], default='Select Category', max_length=50),
        ),
        migrations.AlterField(
            model_name='items',
            name='item_id',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='items',
            name='name',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='items',
            name='pic',
            field=models.FileField(blank=True, null=True, upload_to='images/'),
        ),
        migrations.AlterField(
            model_name='items',
            name='status',
            field=models.CharField(choices=[('Available', 'Available'), ('Unavailable', 'Unavailable')], default='Available', max_length=20),
        ),
    ]
