# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-05-15 13:09
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Website', '0008_auto_20170514_1507'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='item',
            name='status',
        ),
    ]
