# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-24 16:32
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Website', '0009_remove_item_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='QRcode',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='item',
            name='xcord',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='item',
            name='ycord',
            field=models.IntegerField(null=True),
        ),
    ]
