# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-24 17:21
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Website', '0010_auto_20170724_2202'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='category',
            field=models.CharField(choices=[(b'Select category', b'-'), (b'Stationary', b'Stationary'), (b'Eatables', b'Eatables')], default=b'-', max_length=50),
        ),
    ]
