# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-24 17:58
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Website', '0011_auto_20170724_2251'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='cart',
            field=models.TextField(null=True),
        ),
    ]
