# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-30 06:18
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Website', '0020_auto_20170725_1815'),
    ]

    operations = [
        migrations.AlterField(
            model_name='review',
            name='review_date',
            field=models.DateField(null=True),
        ),
    ]
